# Generated by Django 5.2.1 on 2025-05-19 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BahanPakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kadar_air', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bahan_kering', models.DecimalField(decimal_places=2, max_digits=5)),
                ('abu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein_kasar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lemak_kasar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('serat_kasar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('betn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('energi_metabolisme', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calsium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('posfor_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('posfor_tersedia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lys', models.DecimalField(decimal_places=2, max_digits=5)),
                ('met', models.DecimalField(decimal_places=2, max_digits=5)),
                ('met_sis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trypt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaseUnggas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JenisUnggas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formulasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulasi', models.JSONField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faseunggas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unggas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jenisunggas')),
            ],
        ),
        migrations.CreateModel(
            name='BahanFormulasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bahan_pakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bahanpakan')),
                ('formulasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bahan_formulasi', to='core.formulasi')),
            ],
        ),
        migrations.CreateModel(
            name='KebutuhanNutrien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bk_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('abu_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('abu_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pk_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pk_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lk_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lk_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sk_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sk_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('betn_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('betn_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('me_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('me_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ca_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ca_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_total_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_total_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_tersedia_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_tersedia_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lys_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lys_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('met_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('met_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('met_sis_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('met_sis_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tre_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tre_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trypt_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trypt_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faseunggas')),
                ('jenis_unggas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jenisunggas')),
            ],
        ),
    ]
