# Generated by Django 5.2.1 on 2025-05-20 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BahanPakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaseUnggas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('satuan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaseJenisUnggas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faseunggas')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Formulasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_formulasi', models.CharField(blank=True, max_length=100)),
                ('formulasi', models.JSONField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faseunggas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BahanFormulasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bahan_pakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bahanpakan')),
                ('formulasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bahan_formulasi', to='core.formulasi')),
            ],
        ),
        migrations.CreateModel(
            name='JenisUnggas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('fase', models.ManyToManyField(through='core.FaseJenisUnggas', to='core.faseunggas')),
            ],
        ),
        migrations.AddField(
            model_name='formulasi',
            name='unggas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jenisunggas'),
        ),
        migrations.AddField(
            model_name='fasejenisunggas',
            name='jenis_unggas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jenisunggas'),
        ),
        migrations.AlterUniqueTogether(
            name='fasejenisunggas',
            unique_together={('jenis_unggas', 'fase')},
        ),
        migrations.CreateModel(
            name='KebutuhanNutrien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faseunggas')),
                ('jenis_unggas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jenisunggas')),
                ('nutrien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nutrien')),
            ],
            options={
                'unique_together': {('jenis_unggas', 'fase', 'nutrien')},
            },
        ),
        migrations.CreateModel(
            name='KandunganNutrien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bahan_pakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kandungan_nutrien', to='core.bahanpakan')),
                ('nutrien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nutrien')),
            ],
            options={
                'unique_together': {('bahan_pakan', 'nutrien')},
            },
        ),
    ]
