# Generated by Django 5.2.1 on 2025-05-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandungannutrien',
            name='nilai',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
