# Generated by Django 5.2.1 on 2025-05-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_kandungannutrien_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahanpakan',
            name='kategori',
            field=models.CharField(choices=[('energi', 'Sumber Engeri'), ('protein', 'Sumber Protein'), ('mineral', 'Mineral & Prefix')], default='energi', max_length=20),
        ),
    ]
