# Generated by Django 5.2.1 on 2025-05-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bahanpakan_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahanpakan',
            name='kategori',
            field=models.CharField(choices=[('energi', 'Sumber Energi'), ('protein', 'Sumber Protein'), ('mineral', 'Mineral & Prefix')], default='energi', max_length=20),
        ),
    ]
