# Generated by Django 5.2.1 on 2025-06-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bahanpakan_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='bahanpakan',
            name='max_penggunaan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bahanpakan',
            name='min_penggunaan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bahanpakan',
            name='prioritas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
