# Generated by Django 5.2.1 on 2025-06-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_is_active_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulasi',
            name='kandungan_nutrien',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
