# Generated by Django 5.2.1 on 2025-06-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_formulasi_kandungan_nutrien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulasi',
            name='total_harga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
