# Generated by Django 5.2.1 on 2025-06-28 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_formulasi_total_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFormulasiSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faseunggas')),
                ('jenis_unggas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jenisunggas')),
            ],
        ),
        migrations.CreateModel(
            name='BahanLogFormulasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bahan_pakan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bahanpakan')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bahan_log', to='core.logformulasisession')),
            ],
        ),
    ]
